#!/bin/sh
sudo apt update
sudo apt upgrade -y
sudo apt install -y debhelper debmake git fish
curl https://sh.rustup.rs -sSf | sh
rustup target add x86_64-unknown-linux-musl
rustup target add i686-unknown-linux-musl
