#!/bin/sh
git clean -dfx \
 && rm -f ned_1.*.*.orig.tar.gz  ned-1.*.*.tar.gz \
 && uscan -dd \
 && cd ned-1.*.* \
 && debuild -k05ECA9EE -S \
 && cd .. \
 && gpg --verify ned_1.2.6-0ubuntu*_source.changes \
 && dput ppa:nevdelap/ned ned_1.*.*-0ubuntu*_source.changes \
 && cd ned-1.*.*
